if: tag IS present
dist: xenial
language: python
python:
- '3.7'
install:
- pip install wheel
script: echo "No build-time tests to run."
deploy:
  provider: pypi
  user: adamrehn
  distributions: bdist_wheel
  on:
    tags: true
  password:
    secure: datop6PgYGUlDfTx4crYZ1mM1FRIQOFldH+C18V2mRXO4aODOXteWfwI0hyhwtJHKKzetyQRXS18GPejj4/BAivkFnkf/4fQdx12f5VPfdHsXrjJnplXS2PgUllCWaLX5fzF80Mi/eXOqfrnBaS8s8IKWMbkj+hrMetYIvexNG/1YaJ241EA6UTzoToC2SvbUpvWwuwzn9exab+Jb9V3CjWaMi/SoOxJAqDKbFpJlTGhPXjFRuUTgqwMoFXe7X+IYC9+wRjssKH7MlvcC2PhYBeJQYxMWJmZaQGaW5vGgPEoJ4Cr4/hA5bfpigEPTMdRXCUDGTAdG7TD0FX0pdwckgZRCnzepxr3nfcDCEEwMN9CJxBW83GTQK8S8vuHDPk8wR0J1+PpUnuNZcG8HrU6cFIZTiY1H/7O0t+GT8yVL4gMtjqEOU0db0SPXnWeXrn9dOntc9ldP43xbFEhFIhqOdGHp0pV6XNPwb7OijypT1bN1ehmDuKDZrXGz0t5nkYDaeyTMgsb3FhLNk7IGtrThsVMjSVpy5ayAJN2o6w1s+zXtlgF/25k3P6etLtd8KsrddrHPOV7DNgRjjBuJQxZqjXk21gj0HhCaRhb7DHfcBfTYe1pzqHV420hQPktN9SN0FJVMBwOmWKCDw4SY22SdLBJmcyeZ6z8mbpDzHo/Mgk=
